name: Daily Tieba Sign-In

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'  # 北京时间 6:30 (UTC+8)

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build and execute for multiple accounts
        env:
          # 多个账号的BDUSS，用空格分隔
          BDUSS: ${{ secrets.BDUSS }}
          # Server酱的SendKey（用于汇总通知）
          SERVERCHAN_KEY: ${{ secrets.ONE  }}
        run: |
          # 将BDUSS转换为数组
          IFS=' ' read -r -a bduss_array <<< "$BDUSS"
          
          # 初始化结果汇总
          summary=""
          success_count=0
          failure_count=0
          account_count=${#bduss_array[@]}
          
          # 循环处理每个账号
          for i in "${!bduss_array[@]}"; do
            echo "正在处理账号 $((i+1))/$account_count ..."
            BDUSS=${bduss_array[$i]}
            
            # 执行签到并捕获输出
            mvn_output=$(mvn -B compile exec:java \
              -Dexec.mainClass="top.srcrs.Run" \
              -Dexec.args="$BDUSS" 2>&1)  # 移除了SCKEY参数
            
            # 检查执行状态
            status_code=$?
            
            # 记录结果
            if [ $status_code -eq 0 ]; then
              summary+="✅ 账号 $((i+1)): 签到成功\n"
              success_count=$((success_count+1))
            else
              summary+="❌ 账号 $((i+1)): 签到失败\n"
              failure_count=$((failure_count+1))
            fi
          done

          # 构造推送消息
          if [ $failure_count -eq 0 ]; then
            title="贴吧签到成功（$account_count 个账号）"
          else
            title="贴吧签到异常（成功: $success_count, 失败: $failure_count）"
          fi
          
          desp="**执行时间**：$(date +"%Y-%m-%d %H:%M:%S")\n" 
          desp+="**仓库信息**：${{ github.repository }}\n\n"
          desp+="**账号签到结果**：\n$summary"

          # 发送汇总通知
          curl -X POST \
            -d "title=$title" \
            --data-urlencode "desp=$desp" \
            "https://sctapi.ftqq.com/$SERVERCHAN_KEY.send"
