name: Daily Tieba Sign-In

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'  # 北京时间 6:30 (UTC+8)

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build and execute
        env:
          BDUSS_LIST: ${{ secrets.BDUSS_LIST }}  # 使用分号分隔的多个BDUSS
          SCKEY: ${{ secrets.SCKEY }}
          SERVERCHAN_KEY: ${{ secrets.ONE }}
        run: |
          # 将分号分隔的BDUSS转换为数组
          IFS=';' read -ra BDUSS_ARRAY <<< "$BDUSS_LIST"
          
          # 循环处理每个BDUSS
          for BDUSS in "${BDUSS_ARRAY[@]}"
          do
            # 去除可能的首尾空格
            BDUSS=$(echo $BDUSS | xargs)
            
            # 打印当前处理的账号（后6位用于标识）
            echo "处理账号: ${BDUSS: -6}..."
            
            # 运行签到脚本并捕获输出日志
            mvn_output=$(mvn -B compile exec:java \
              -Dexec.mainClass="top.srcrs.Run" \
              -Dexec.args="$BDUSS $SCKEY" 2>&1)

            # 获取命令执行状态码
            status_code=$?

            # 根据状态码构造推送消息
         
            sleep 5
          done
